# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/RO_constr.xdc

# Block Designs: bd/Base_Zynq_MPSoC/Base_Zynq_MPSoC.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC || ORIG_REF_NAME==Base_Zynq_MPSoC} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_zynq_ultra_ps_e_0_0/Base_Zynq_MPSoC_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_axi_gpio_0_0/Base_Zynq_MPSoC_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_axi_gpio_0_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_xbar_0/Base_Zynq_MPSoC_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_xbar_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_xbar_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_ps8_0_axi_periph_0/Base_Zynq_MPSoC_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_ps8_0_axi_periph_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_rst_ps8_0_100M_0/Base_Zynq_MPSoC_rst_ps8_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_rst_ps8_0_100M_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_system_management_wiz_0_0/Base_Zynq_MPSoC_system_management_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_system_management_wiz_0_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_axi_gpio_1_0/Base_Zynq_MPSoC_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_axi_gpio_1_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_axi_gpio_2_0/Base_Zynq_MPSoC_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_axi_gpio_2_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_Simulated_Load_IP_Co_0_0/Base_Zynq_MPSoC_Simulated_Load_IP_Co_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_Simulated_Load_IP_Co_0_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_Simulated_Load_IP_Co_0_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_pwm_0_1/Base_Zynq_MPSoC_pwm_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_pwm_0_1 || ORIG_REF_NAME==Base_Zynq_MPSoC_pwm_0_1} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_Measurement_Load_0_1/Base_Zynq_MPSoC_Measurement_Load_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_Measurement_Load_0_1 || ORIG_REF_NAME==Base_Zynq_MPSoC_Measurement_Load_0_1} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_auto_ds_0/Base_Zynq_MPSoC_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_auto_ds_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_auto_ds_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_auto_pc_0/Base_Zynq_MPSoC_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_auto_pc_0 || ORIG_REF_NAME==Base_Zynq_MPSoC_auto_pc_0} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_auto_ds_1/Base_Zynq_MPSoC_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_auto_ds_1 || ORIG_REF_NAME==Base_Zynq_MPSoC_auto_ds_1} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_auto_pc_1/Base_Zynq_MPSoC_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_auto_pc_1 || ORIG_REF_NAME==Base_Zynq_MPSoC_auto_pc_1} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_auto_ds_2/Base_Zynq_MPSoC_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_auto_ds_2 || ORIG_REF_NAME==Base_Zynq_MPSoC_auto_ds_2} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_auto_pc_2/Base_Zynq_MPSoC_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_auto_pc_2 || ORIG_REF_NAME==Base_Zynq_MPSoC_auto_pc_2} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_auto_ds_3/Base_Zynq_MPSoC_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_auto_ds_3 || ORIG_REF_NAME==Base_Zynq_MPSoC_auto_ds_3} -quiet] -quiet

# IP: bd/Base_Zynq_MPSoC/ip/Base_Zynq_MPSoC_auto_pc_3/Base_Zynq_MPSoC_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Zynq_MPSoC_auto_pc_3 || ORIG_REF_NAME==Base_Zynq_MPSoC_auto_pc_3} -quiet] -quiet

# XDC: bd/Base_Zynq_MPSoC/Base_Zynq_MPSoC_ooc.xdc
